### PR TITLE
Progress update...

### PR DESCRIPTION
**Pull request by Selameab**
New Features: 
* Partially working settings window
* Responsive windows
* Atom selection
* Anchor-able atoms

### CODE REVIEW

**Comment by AmeBel** [comment]
@eddiemonroe please reveiew and merge

**Comment by eddiemonroe** [comment]
@AmeBel I can review functionality, but I don't know js, so not a good match if code review is wanted.

@Selameab Is the visualizer ready for functional review? (Doesn't look like it's pulling atoms from an atomspace to me.)
Will anyone wanting to use this visualizer need to install npm and bower and start up a server?

**Comment by AmeBel** [comment]
@eddiemonroe since you know what the functionalities that are required checking against the required behaviors will do. Once @Selameab add functional tests then it could be automated.

**Comment by Selameab** [comment]
@AmeBel : I'll add unit tests after the urgent functionalities are completed...
@eddiemonroe : I don't think it is. All the tasks completed so far are simple features. Getting it to pull from the atomspace is a matter of changing a single line. But I'm having trouble getting the restapi to run after a pull a month ago. Actually, the real issue is getting loadpy to show up on the opencog shell. Any help on this is truly appreciated.

npm and bower are used to install third party libraries. @AmeBel suggested that it's bad practice to include third party code in VC. 

The server is needed to deal with browser cache issues. Angular has a "bad" reputation at caching old js files. For the release version, it should be as simple as opening "index.html" ...

**Comment by AmeBel** [comment]
@Selameab open an issue @ https://github.com/opencog/opencog detailing the problem and steps for reproducing it .

**Comment by eddiemonroe** [comment]
@Selameab: Thanks. So will npm and bower need to be installed for using the release version, or are those just for the server?

**Comment by Selameab** [comment]
@eddiemonroe: We could bundle third party libraries into the release version so that npm and bower won't be needed. @AmeBel : Is it acceptable?

**Comment by AmeBel** [comment]
Assuming the main use case is for it to be deployed on a server, you can add the libraries during dockerization.

**Comment by eddiemonroe** [comment]
@AmeBel: My interpretation of what @Selameab was meaning is that the server is being used for development purposes (because of angular cache issues), but that the release version would not need the server ("For the release version, it should be as simple as opening "index.html"). Though I wouldn't bet a lot of money that I am understanding correctly...

**Comment by AmeBel** [comment]
@eddiemonroe  as long as the libraries required by index.html are available on the host( which I refered to as a server on the previous comment) all will be fine. npm and bower , as far as I know, are merely being used as tools for downloading the dependencies, as vedoring in the libraries  with the source is frowned upon as a practice. You can replace them with a shell script for that matter or make the html  `link` tags point to the URI of the required dependencies(assuming offline usage isn't needed).

@Selameab I just observered you have set the licence to be `MIT` has there been a decision on this?

**Comment by Selameab** [comment]
@AmeBel: No, I just went with bower's default.

**Comment by AmeBel** [comment]
Maybe using the `link` tag that point to a URI might not be a good idea http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

**Pull request merged**
