### PR TITLE
Glimpse - Initial PR

### PR DESCRIPTION
**Pull request by Selameab**
Angular based viewer for atomspace....

### CODE REVIEW

**Comment by Selameab** [comment]
This doesn't require the cogserver and restapi to run. I've included a test json for development purposes.

**Comment by linas** [comment]
what does it require?

I'm moving to designs which don't use a cogserver ... is it possible to get the needed atoms, etc. without using a cogserver?

**Comment by Selameab** [comment]
This will finally need the rest api to query the atoms.

I'm using test jsons because some of us had trouble getting the rest api to load on recent commits...

**Comment by AmeBel** [comment]
Merged, haven't tested it though.

**Pull request merged**
