### PR TITLE
Improved Glimpse Atomspace Visualizer

### PR DESCRIPTION
**Pull request by tanksha**

### CODE REVIEW

**Comment by linas** [comment]
As a matter of proceedure --- why are we placing disparate, unrelated tools into one and the same repo?  Isn't it a much better idea to create a distinct repo called `opencog/glimpse` to hold this code?

**Comment by AmeBel** [comment]
@linas this repo is meant for disparate tools that don't necessarily form the core of opencog. Tools for importing data-sets into atomspace and for visualization content of atomspace, presently.

**Comment by AmeBel** [comment]
@tanksha Can't merge b/c there is merge conflict. Please merge opencog/external-tools master branch on to the branch you made this pr from.

**Comment by linas** [comment]
Amen, yes, but why? why not create a distinct repo e.g. https://github.com/opencog/glimpse

**Comment by AmeBel** [comment]
I have no reason to create or not create one. I am cool with whatever the core-team decide on.

**Comment by linas** [comment]
When two things share common code, you put it in one repo. But when there is nothing in common at all, it doesn't make sense .. everything gets harder.

The problem with everything in one repo is you end up with old obsolete crap that no longer works, but everyone has to support because of unit tests, etc. 

Another problem is dealing with pull requests: some you can ignore, some you have to pay attention to, depending on which component they are for.

Then there are the bug reports: you might have 10 open bug reports, but they are all for the dead, obsolete component.  They get in the way, and hide the bug reports for the one or two components that you do care about.

There's also the issue of install dependencies -- having to install dependencies for things that never actually get used... 

Management and operation just get worse in almost every way.

**Pull request merged**
