### PR TITLE
Theta

### PR DESCRIPTION
**Pull request by skoumas**
New features : 
- Listing of Cogservers
- Right Panel

### CODE REVIEW

**Comment by AmeBel** [comment]
Maybe the following are work in progress, but just wanted to point them out, as a reminder
* On sigma views, the Grid and Cluster are not working. 
* Atom details dialog box doesn't have a close button.

**Comment by AmeBel** [comment]
What do you mean by listing of cogservers?

**Comment by skoumas** [comment]
A new function is implemented that allows the user to save a cogserver for future use and select it from the List of Cogservers in case working with multiple cogserver sources.

**Comment by AmeBel** [comment]
OK great, that is useful.

A suggestion, the visualizer has two use cases,
1. as a desktop interface which is the usual case
2. the other we had deployed it on a server a while back. It would be great if there is deployment state, wherein if it finds a certain environment variable (let say OPENCOG_COGSERVER_ADDRESS) and it has a proper ip-address/hostname then it would use that and the server address box is hidden.

**Comment by skoumas** [comment]
Yeap about the OPENCOG enviroment variable sounds handy. If there is an option to connect system variables via jquery or javascript or HTML5 happy to do so but not sure if the web browser framework supports this currently.

**Pull request merged**
