### PR TITLE
Oc viewer

### PR DESCRIPTION
**Pull request by skoumas**
So this is the first pull for the new visualizer. The main folder can be found under ocViewer.

### CODE REVIEW

**Comment by AmeBel** [comment]
having problem connecting to cogserver

**Comment by skoumas** [comment]
Did you check http://localhost:5000 on the connecting tab?

**Comment by AmeBel** [comment]
yes i did

**Comment by skoumas** [comment]
Latest push included missing terminal.js and other files

**Comment by skoumas** [comment]
Terminal commands (View>Terminal) so far are:
Connect
Zoom (atomHandle)
Select (atomHandle)

Waiting for the CORS server side to go to the updating/deleting/pushing new atoms.

**Comment by AmeBel** [comment]
Thanks :smile:

**Pull request merged**
