### PR TITLE
D3hypergraph

### PR DESCRIPTION
**Pull request by tseg**

### CODE REVIEW

**Comment by AmeBel** [comment]
@tseg rebase and push c http://wiki.opencog.org/w/Development_standards#Git_HOWTO

**Comment by AmeBel** [comment]
@tseg please remove the .metadata directory and other files and directories associated with your tools .

Most of the files changes are change in mods, is it required? If so why ?

**Comment by AmeBel** [comment]
some more cleanups are required. 

1. If you run git log you would find the author field associated with info from you pc. If you don't want your work to be associated with your name then it is ok , but if you do then use git config to set it up.
2. The unnecessary directories are still there

**Comment by AmeBel** [comment]
[here](https://help.github.com/articles/changing-author-info/) is a link for a script to auto rewrite the history after you change the config. Reminder backup your work before running script :-)

**Comment by AmeBel** [comment]
@tseg i just run it on a sample data looks cool :+1:

**Comment by tseg** [comment]
Tanks

**Comment by AmeBel** [comment]
@tseg i am merging this as we have new team member at HK who will be working on this.

**Pull request merged**
